/**
 * Catatan Pintar 1.0.3 Feature Pack
 *
 * Fitur baru diimplementasikan sebagai modul terpisah agar tidak mengubah
 * storage lama secara destruktif. Referensi fitur: dashboard keuangan,
 * jadwal/kalender, batch action, kategori cepat, dan anotasi gambar.
 */
import { ImageEditorService } from './imageEditor.js';
import { SecurityService } from './security.js';

const OBL_KEY = 'cp_obligations_v1';
const SAV_KEY = 'cp_savings_v1';
const esc = (v) => SecurityService.escapeHtml(String(v ?? ''));
const rupiah = (v) => 'Rp ' + Number(v || 0).toLocaleString('id-ID');
const id = (p='x') => `${p}_${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`;
const loadJSON = (k, fallback=[]) => { try { const x=JSON.parse(localStorage.getItem(k)); return Array.isArray(x)?x:fallback; } catch { return fallback; } };
const saveJSON = (k,v) => localStorage.setItem(k, JSON.stringify(v));

function addStyle() {
  if (document.getElementById('cp103-style')) return;
  const s=document.createElement('style'); s.id='cp103-style';
  s.textContent=`
    .cp103-nav{position:fixed;left:50%;bottom:10px;transform:translateX(-50%);z-index:90;display:flex;gap:5px;padding:6px;background:rgba(255,252,244,.96);border:1px solid var(--card-edge,#ddd);border-radius:18px;box-shadow:0 8px 30px rgba(0,0,0,.16);backdrop-filter:blur(8px)}
    .cp103-nav button{border:0;background:transparent;padding:8px 13px;border-radius:13px;font:600 12px inherit;color:var(--ink-soft,#667);cursor:pointer}.cp103-nav button.active{background:var(--ink,#27352b);color:#fff}
    .cp103-panel{position:fixed;inset:0;z-index:80;background:var(--paper,#f8f4e9);overflow:auto;padding:18px 14px 100px;display:none}.cp103-panel.open{display:block}
    .cp103-head{max-width:900px;margin:0 auto 12px;display:flex;align-items:center;justify-content:space-between;gap:10px}.cp103-title{font:700 22px 'Source Serif 4',Georgia,serif}.cp103-actions{display:flex;gap:6px;flex-wrap:wrap}.cp103-btn{border:1px solid var(--card-edge,#ddd);background:#fff;border-radius:8px;padding:7px 10px;font-size:12px;font-weight:700;cursor:pointer}.cp103-btn.primary{background:var(--ink,#27352b);color:#fff;border-color:var(--ink,#27352b)}
    .cp103-grid{max-width:900px;margin:0 auto;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.cp103-card{background:#fff;border:1px solid var(--card-edge,#ddd);border-radius:10px;padding:12px;box-shadow:0 2px 8px rgba(0,0,0,.04)}.cp103-card h3{margin:0 0 6px;font:700 14px 'Source Serif 4',Georgia,serif}.cp103-val{font:700 18px 'IBM Plex Mono',monospace}.cp103-muted{font-size:11px;color:var(--ink-soft,#667)}
    .cp103-wide{grid-column:1/-1}.cp103-table{width:100%;border-collapse:collapse;font-size:12px}.cp103-table th,.cp103-table td{text-align:left;padding:7px;border-bottom:1px solid #ece8dc}.cp103-table th{font-size:10px;color:var(--ink-soft,#667);text-transform:uppercase}.cp103-scroll{overflow:auto;max-height:300px}.cp103-input{width:100%;box-sizing:border-box;border:1px solid var(--card-edge,#ddd);border-radius:7px;padding:8px;background:#fff}.cp103-row{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.cp103-row>*{flex:1}.cp103-pill{display:inline-flex;align-items:center;gap:5px;padding:5px 8px;border-radius:999px;border:1px solid #ddd;font-size:11px;background:#fff}.cp103-bar{height:9px;border-radius:8px;background:#eee9dc;overflow:hidden}.cp103-bar>i{display:block;height:100%;background:var(--moss,#47593f)}
    .cp103-cal{display:grid;grid-template-columns:repeat(7,1fr);gap:3px}.cp103-day{min-height:58px;border:1px solid #e7e1d3;background:#fff;border-radius:6px;padding:5px;font-size:11px;cursor:pointer}.cp103-day.muted{opacity:.42}.cp103-day.sel{outline:2px solid var(--ink,#27352b)}.cp103-day b{display:block;margin-bottom:4px}.cp103-dot{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:9px;margin-top:2px;padding:1px 3px;border-radius:4px;background:#f3ead2}
    .cp103-modal{position:fixed;inset:0;background:rgba(0,0,0,.5);z-index:150;display:none;align-items:center;justify-content:center;padding:12px}.cp103-modal.open{display:flex}.cp103-dialog{width:min(850px,100%);max-height:92vh;overflow:auto;background:#fffdf7;border-radius:12px;border:1px solid #ddd5c5;padding:14px}.cp103-tools{display:flex;gap:5px;flex-wrap:wrap;margin:8px 0}.cp103-tools button{padding:6px 8px;border:1px solid #ddd;border-radius:7px;background:#fff;cursor:pointer;font-size:11px}.cp103-canvas-wrap{overflow:auto;background:#eee9dc;padding:8px;border-radius:8px;text-align:center}.cp103-canvas-wrap canvas{max-width:100%;touch-action:none}
    .cp103-batch{position:fixed;left:10px;right:10px;bottom:74px;z-index:89;display:none;background:#fffdf7;border:1px solid #d8d0bf;border-radius:12px;padding:8px;box-shadow:0 8px 24px rgba(0,0,0,.14)}.cp103-batch.open{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.cp103-batch button{border:1px solid #ddd;background:#fff;border-radius:7px;padding:6px 8px;font-size:11px;font-weight:700}
    @media(max-width:650px){.cp103-grid{grid-template-columns:1fr}.cp103-wide{grid-column:auto}.cp103-nav button{padding:8px 10px}.cp103-title{font-size:19px}}
  `; document.head.appendChild(s);
}

export const FeaturePackService = {
  ctx:null, finance:null, obligations:[], savings:[], calDate:new Date(), selectedDate:new Date().toISOString().slice(0,10),
  init(ctx){
    this.ctx=ctx; addStyle(); this.obligations=loadJSON(OBL_KEY); this.savings=loadJSON(SAV_KEY); this.buildShell(); this.buildEditorExtras(); this.bind(); this.renderFinance(); this.renderCalendar(); this.syncBatchBar();
  },
  buildShell(){
    if(document.getElementById('cp103Nav')) return;
    const nav=document.createElement('nav');nav.id='cp103Nav';nav.className='cp103-nav';nav.innerHTML='<button data-tab="home" class="active">📝 Catatan</button><button data-tab="finance">💰 Keuangan</button><button data-tab="schedule">📅 Jadwal</button>';document.body.appendChild(nav);
    const fin=document.createElement('section');fin.id='cp103Finance';fin.className='cp103-panel';fin.innerHTML=`<div class="cp103-head"><div><div class="cp103-title">💰 Keuangan</div><div class="cp103-muted">Ringkasan pemasukan, pengeluaran, hutang, kewajiban dan tabungan.</div></div><div class="cp103-actions"><button class="cp103-btn" id="cp103ExportFinance">Ekspor</button><button class="cp103-btn primary" id="cp103AddIncome">+ Pemasukan</button><button class="cp103-btn" id="cp103AddExpense">+ Pengeluaran</button><button class="cp103-btn" id="cp103AddDebt">+ Hutang</button></div></div><div class="cp103-grid"><div class="cp103-card"><div class="cp103-muted">Pemasukan</div><div class="cp103-val" id="cp103Income">Rp 0</div></div><div class="cp103-card"><div class="cp103-muted">Pengeluaran</div><div class="cp103-val" id="cp103Expense">Rp 0</div></div><div class="cp103-card"><div class="cp103-muted">Saldo Bersih</div><div class="cp103-val" id="cp103Balance">Rp 0</div></div><div class="cp103-card"><div class="cp103-muted">Hutang Aktif</div><div class="cp103-val" id="cp103Debt">Rp 0</div></div><div class="cp103-card"><div class="cp103-muted">Kewajiban Belum Lunas</div><div class="cp103-val" id="cp103Obligation">Rp 0</div></div><div class="cp103-card"><div class="cp103-muted">Total Tabungan</div><div class="cp103-val" id="cp103Savings">Rp 0</div></div><div class="cp103-card cp103-wide"><div class="cp103-row"><input class="cp103-input" type="date" id="cp103FinFrom"><input class="cp103-input" type="date" id="cp103FinTo"><button class="cp103-btn" id="cp103ResetFin">Semua tanggal</button></div><div style="height:10px"></div><div id="cp103FinanceChart"></div></div><div class="cp103-card"><h3>Pemasukan & Pengeluaran</h3><div class="cp103-scroll" id="cp103TxList"></div></div><div class="cp103-card"><h3>Hutang</h3><div class="cp103-scroll" id="cp103DebtList"></div></div><div class="cp103-card cp103-wide"><div class="cp103-row"><h3 style="margin-right:auto">Dana Pengeluaran Wajib</h3><button class="cp103-btn" id="cp103AddOb">+ Tambah</button></div><div class="cp103-row"><input class="cp103-input" id="cp103ObName" placeholder="Nama kewajiban"><input class="cp103-input" id="cp103ObAmount" type="number" min="0" placeholder="Nominal"><input class="cp103-input" id="cp103ObDue" placeholder="Jatuh tempo"></div><div class="cp103-scroll" id="cp103ObList"></div></div><div class="cp103-card cp103-wide"><div class="cp103-row"><h3 style="margin-right:auto">Pos Tabungan</h3><button class="cp103-btn" id="cp103AddSav">+ Pos Baru</button><button class="cp103-btn" id="cp103DepositSav">Setor / Tarik</button></div><div class="cp103-scroll" id="cp103SavList"></div></div></div>`;document.body.appendChild(fin);
    const sch=document.createElement('section');sch.id='cp103Schedule';sch.className='cp103-panel';sch.innerHTML=`<div class="cp103-head"><div><div class="cp103-title">📅 Jadwal & Acara</div><div class="cp103-muted">Kalender bulanan untuk catatan kategori Acara.</div></div><div class="cp103-actions"><button class="cp103-btn" id="cp103Prev">‹ Bulan</button><button class="cp103-btn" id="cp103Today">Hari ini</button><button class="cp103-btn" id="cp103Next">Bulan ›</button><button class="cp103-btn primary" id="cp103AddEvent">+ Acara</button></div></div><div class="cp103-card" style="max-width:900px;margin:auto"><div class="cp103-head" style="margin:0 0 8px"><b id="cp103Month"></b><span class="cp103-muted" id="cp103SelCount"></span></div><div class="cp103-cal" id="cp103Calendar"></div><div style="height:12px"></div><h3>Acara pada tanggal terpilih</h3><div class="cp103-scroll" id="cp103DayEvents"></div></div>`;document.body.appendChild(sch);
    const batch=document.createElement('div');batch.id='cp103Batch';batch.className='cp103-batch';batch.innerHTML='<b id="cp103BatchCount">0 dipilih</b><button id="cp103BatchDelete">Hapus</button><button id="cp103BatchMove">Pindah Kategori</button><button id="cp103BatchExport">Ekspor</button>';document.body.appendChild(batch);
  },
  buildEditorExtras(){
    const cat=document.getElementById('categorySelect');
    if(cat && !document.getElementById('cp103QuickCat')){const b=document.createElement('button');b.type='button';b.id='cp103QuickCat';b.className='btn-subtle';b.textContent='＋ Kategori';b.style.marginLeft='6px';cat.parentElement?.appendChild(b);}
    const fin=document.getElementById('financeRow');
    if(fin && !document.getElementById('cp103IncomeFrom')){
      const wrap=document.createElement('div');wrap.id='cp103FinanceExtra';wrap.style.cssText='display:flex;gap:8px;flex-wrap:wrap;margin-top:6px';wrap.innerHTML='<input id="cp103IncomeFrom" class="cp103-input" style="flex:1" placeholder="Pemasukan dari siapa / sumber"><input id="cp103ExpenseFor" class="cp103-input" style="flex:1;display:none" placeholder="Pengeluaran untuk apa">';fin.parentElement?.appendChild(wrap);
    }
    const rem=document.getElementById('reminderRow');
    if(rem && !document.getElementById('cp103EventLocation')){const row=document.createElement('div');row.id='cp103ScheduleExtra';row.style.cssText='display:none;margin-top:8px';row.innerHTML='<label style="font-size:12px;font-weight:600">Lokasi acara</label><input id="cp103EventLocation" class="cp103-input" placeholder="Contoh: Rumah, kantor, sekolah"><input id="cp103EventDate" type="hidden">';rem.parentElement?.appendChild(row);}
    if(document.getElementById('toolbar') && !document.getElementById('cp103ImageBtn')){const b=document.createElement('button');b.type='button';b.id='cp103ImageBtn';b.className='toolbar-btn';b.textContent='🖼️ Anotasi';b.title='Tambah gambar lalu beri anotasi';document.getElementById('toolbar').appendChild(b);}
  },
  bind(){
    document.querySelectorAll('#cp103Nav button').forEach(b=>b.onclick=()=>this.switchTab(b.dataset.tab));
    document.getElementById('cp103AddIncome').onclick=()=>this.ctx.openFinance('income');document.getElementById('cp103AddExpense').onclick=()=>this.ctx.openFinance('expense');document.getElementById('cp103AddDebt').onclick=()=>this.ctx.openFinance('debt');
    document.getElementById('cp103ExportFinance').onclick=()=>this.exportFinance();document.getElementById('cp103FinFrom').onchange=()=>this.renderFinance();document.getElementById('cp103FinTo').onchange=()=>this.renderFinance();document.getElementById('cp103ResetFin').onclick=()=>{document.getElementById('cp103FinFrom').value='';document.getElementById('cp103FinTo').value='';this.renderFinance();};
    document.getElementById('cp103AddOb').onclick=()=>this.addObligation();document.getElementById('cp103AddSav').onclick=()=>this.addSavings();document.getElementById('cp103DepositSav').onclick=()=>this.transactSavings();
    document.getElementById('cp103Prev').onclick=()=>{this.calDate.setMonth(this.calDate.getMonth()-1);this.renderCalendar();};document.getElementById('cp103Next').onclick=()=>{this.calDate.setMonth(this.calDate.getMonth()+1);this.renderCalendar();};document.getElementById('cp103Today').onclick=()=>{this.calDate=new Date();this.selectedDate=new Date().toISOString().slice(0,10);this.renderCalendar();};document.getElementById('cp103AddEvent').onclick=()=>this.ctx.openSchedule(this.selectedDate);
    const syncEditorExtras=()=>{
      const category=document.getElementById('categorySelect')?.value;
      const type=document.getElementById('financeType')?.value;
      const eventRow=document.getElementById('cp103ScheduleExtra');
      const financeRow=document.getElementById('cp103FinanceExtra');
      if(eventRow) eventRow.style.display=category==='acara'?'block':'none';
      if(financeRow) financeRow.style.display=category==='keuangan'?'flex':'none';
      const income=document.getElementById('cp103IncomeFrom');
      const expense=document.getElementById('cp103ExpenseFor');
      if(income) income.style.display=category==='keuangan'&&type==='income'?'block':'none';
      if(expense) expense.style.display=category==='keuangan'&&type==='expense'?'block':'none';
    };
    document.getElementById('categorySelect')?.addEventListener('change',syncEditorExtras);
    document.getElementById('financeType')?.addEventListener('change',syncEditorExtras);
    syncEditorExtras();
    document.getElementById('cp103QuickCat')?.addEventListener('click',async()=>{const name=prompt('Nama kategori baru:');if(!name?.trim())return;const icon=prompt('Ikon (opsional):','📁')||'📁';await this.ctx.addCategory({id:id('cat'),name:name.trim(),icon, color:'#3d5a6b',core:false});});
    document.getElementById('cp103ImageBtn')?.addEventListener('click',()=>this.openImageEditor());
    document.getElementById('cp103BatchDelete').onclick=()=>this.batchDelete();document.getElementById('cp103BatchMove').onclick=()=>this.batchMove();document.getElementById('cp103BatchExport').onclick=()=>this.batchExport();
    document.addEventListener('cp103:refresh',()=>{this.renderFinance();this.renderCalendar();this.syncBatchBar();});
    setInterval(()=>this.syncBatchBar(),700);
  },
  switchTab(tab){
    const fin=document.getElementById('cp103Finance'),sch=document.getElementById('cp103Schedule');
    fin.classList.toggle('open',tab==='finance');sch.classList.toggle('open',tab==='schedule');
    document.querySelectorAll('#cp103Nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
    if(tab==='finance')this.renderFinance();if(tab==='schedule')this.renderCalendar();
  },
  getTx(){
    const notes=this.ctx.getNotes();const from=document.getElementById('cp103FinFrom')?.value;const to=document.getElementById('cp103FinTo')?.value;const f=from?new Date(from+'T00:00:00').getTime():0;const t=to?new Date(to+'T23:59:59').getTime():Infinity;
    return notes.filter(n=>n.category==='keuangan'&&n.finance).filter(n=>{const ts=n.updatedAt||n.createdAt;return ts>=f&&ts<=t}).map(n=>({...n, amount:Number(n.finance.amount)||0,type:n.finance.type||'expense'})).sort((a,b)=>(b.updatedAt||b.createdAt)-(a.updatedAt||a.createdAt));
  },
  renderFinance(){
    const tx=this.getTx();const income=tx.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0),expense=tx.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0),debt=tx.filter(x=>x.type==='debt'&&!x.finance.debtPaid).reduce((a,x)=>a+x.amount,0),obl=this.obligations.filter(x=>!x.isPaid).reduce((a,x)=>a+Number(x.amount||0),0),sav=this.savings.reduce((a,x)=>a+Number(x.balance||0),0);
    for(const [k,v] of Object.entries({Income:income,Expense:expense,Balance:income-expense,Debt:debt,Obligation:obl,Savings:sav})){const el=document.getElementById('cp103'+k);if(el)el.textContent=rupiah(v)}
    const chart=document.getElementById('cp103FinanceChart');const max=Math.max(income,expense,1);chart.innerHTML=`<div class="cp103-muted">Arus kas</div><div style="display:flex;gap:10px;align-items:flex-end;height:100px;margin-top:8px"><div style="flex:1;text-align:center"><div class="cp103-bar"><i style="width:${Math.round(income/max*100)}%"></i></div><small>Pemasukan<br>${rupiah(income)}</small></div><div style="flex:1;text-align:center"><div class="cp103-bar"><i style="width:${Math.round(expense/max*100)}%;background:var(--danger,#a3402f)"></i></div><small>Pengeluaran<br>${rupiah(expense)}</small></div><div style="flex:1;text-align:center"><div class="cp103-bar"><i style="width:${Math.round(debt/max*100)}%;background:#b8922f"></i></div><small>Hutang<br>${rupiah(debt)}</small></div></div>`;
    const list=document.getElementById('cp103TxList');list.innerHTML=tx.length?tx.slice(0,50).map(n=>`<div style="padding:7px;border-bottom:1px solid #eee8dc;cursor:pointer" data-note="${esc(n.id)}"><b>${esc(n.title)}</b><div class="cp103-muted">${n.type==='income'?'+':'-'} ${rupiah(n.amount)}</div></div>`).join(''):'<div class="cp103-muted">Belum ada transaksi.</div>';list.querySelectorAll('[data-note]').forEach(x=>x.onclick=()=>{this.switchTab('home');this.ctx.openNote(x.dataset.note)});
    const debts=tx.filter(n=>n.type==='debt');document.getElementById('cp103DebtList').innerHTML=debts.length?debts.map(n=>`<div style="padding:7px;border-bottom:1px solid #eee8dc"><b>${esc(n.title)}</b><div class="cp103-muted">${esc(n.finance.debtTo||'-')} · ${rupiah(n.amount)} · ${n.finance.debtPaid?'Lunas':'Belum lunas'}</div></div>`).join(''):'<div class="cp103-muted">Belum ada hutang.</div>';
    document.getElementById('cp103ObList').innerHTML=this.obligations.length?this.obligations.map((o,i)=>`<div style="display:flex;gap:8px;align-items:center;padding:7px;border-bottom:1px solid #eee8dc"><span style="flex:1"><b>${esc(o.name)}</b><div class="cp103-muted">${esc(o.dueDate||'')} · ${rupiah(o.amount)}</div></span><button class="cp103-btn" data-ob="${i}">${o.isPaid?'Belum lunas':'Lunasi'}</button><button class="cp103-btn" data-ob-del="${i}">×</button></div>`).join(''):'<div class="cp103-muted">Belum ada kewajiban.</div>';
    const obList=document.getElementById('cp103ObList');obList.querySelectorAll('[data-ob]').forEach(b=>b.onclick=()=>{this.obligations[Number(b.dataset.ob)].isPaid=!this.obligations[Number(b.dataset.ob)].isPaid;saveJSON(OBL_KEY,this.obligations);this.renderFinance();});obList.querySelectorAll('[data-ob-del]').forEach(b=>b.onclick=()=>{this.obligations.splice(Number(b.dataset.obDel),1);saveJSON(OBL_KEY,this.obligations);this.renderFinance();});
    const sl=document.getElementById('cp103SavList');sl.innerHTML=this.savings.length?this.savings.map((s,i)=>{const pct=s.target?Math.min(100,Math.round(Number(s.balance||0)/Number(s.target)*100)):0;return `<div style="padding:8px;border-bottom:1px solid #eee8dc"><div class="cp103-row"><b style="flex:1">${esc(s.name)}</b><span>${rupiah(s.balance)} / ${rupiah(s.target)}</span><button class="cp103-btn" data-sav-del="${i}">×</button></div><div class="cp103-bar"><i style="width:${pct}%"></i></div><div class="cp103-muted">${pct}%${s.source?' · sumber: '+esc(s.source):''}</div></div>`}).join(''):'<div class="cp103-muted">Belum ada pos tabungan.</div>';sl.querySelectorAll('[data-sav-del]').forEach(b=>b.onclick=()=>{this.savings.splice(Number(b.dataset.savDel),1);saveJSON(SAV_KEY,this.savings);this.renderFinance();});
  },
  addObligation(){const name=document.getElementById('cp103ObName').value.trim();const amount=Number(document.getElementById('cp103ObAmount').value)||0;const due=document.getElementById('cp103ObDue').value.trim();if(!name||amount<=0)return alert('Isi nama dan nominal kewajiban.');this.obligations.push({id:id('ob'),name,amount,dueDate:due,isPaid:false});saveJSON(OBL_KEY,this.obligations);document.getElementById('cp103ObName').value='';document.getElementById('cp103ObAmount').value='';document.getElementById('cp103ObDue').value='';this.renderFinance();},
  addSavings(){const name=prompt('Nama pos tabungan:');if(!name?.trim())return;const target=Number(prompt('Target tabungan (Rp):','1000000'))||0;const source=prompt('Sumber utama (opsional):','')||'';this.savings.push({id:id('sav'),name:name.trim(),target,balance:0,source});saveJSON(SAV_KEY,this.savings);this.renderFinance();},
  transactSavings(){if(!this.savings.length)return alert('Buat pos tabungan terlebih dahulu.');const opts=this.savings.map((s,i)=>`${i+1}. ${s.name} (${rupiah(s.balance)})`).join('\n');const idx=Number(prompt(`Pilih pos:\n${opts}\nNomor:`))-1;if(!this.savings[idx])return;const type=prompt('Ketik SETOR atau TARIK:','SETOR')?.toLowerCase();const amt=Number(prompt('Nominal (Rp):','50000'))||0;if(amt<=0)return;if(type==='tarik'||type==='withdraw')this.savings[idx].balance=Math.max(0,Number(this.savings[idx].balance||0)-amt);else this.savings[idx].balance=Number(this.savings[idx].balance||0)+amt;saveJSON(SAV_KEY,this.savings);this.renderFinance();},
  exportFinance(){const payload={app:'Catatan Pintar',version:'1.0.3',exportedAt:new Date().toISOString(),transactions:this.getTx().map(n=>({title:n.title,type:n.type,amount:n.amount,date:n.updatedAt||n.createdAt,finance:n.finance})),obligations:this.obligations,savings:this.savings};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='catatan-pintar-keuangan-1.0.3.json';a.click();URL.revokeObjectURL(a.href);},
  eventDate(n){if(n.eventDate)return String(n.eventDate).slice(0,10);if(n.reminder?.datetime)return String(n.reminder.datetime).slice(0,10);return new Date(n.updatedAt||n.createdAt).toISOString().slice(0,10);},
  renderCalendar(){const y=this.calDate.getFullYear(),m=this.calDate.getMonth();const first=new Date(y,m,1).getDay();const days=new Date(y,m+1,0).getDate();document.getElementById('cp103Month').textContent=new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric'}).format(this.calDate);const cal=document.getElementById('cp103Calendar');cal.innerHTML=['Min','Sen','Sel','Rab','Kam','Jum','Sab'].map(x=>`<div class="cp103-muted" style="text-align:center;font-weight:700;padding:4px">${x}</div>`).join('');for(let i=0;i<first;i++)cal.insertAdjacentHTML('beforeend','<div class="cp103-day muted"></div>');for(let d=1;d<=days;d++){const ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;const events=this.ctx.getNotes().filter(n=>n.category==='acara'&&this.eventDate(n)===ds);const cell=document.createElement('div');cell.className='cp103-day'+(ds===this.selectedDate?' sel':'');cell.innerHTML=`<b>${d}</b>${events.slice(0,3).map(n=>`<span class="cp103-dot">🎉 ${esc(n.title)}</span>`).join('')}`;cell.onclick=()=>{this.selectedDate=ds;this.renderCalendar();};cal.appendChild(cell);}const ev=this.ctx.getNotes().filter(n=>n.category==='acara'&&this.eventDate(n)===this.selectedDate);document.getElementById('cp103SelCount').textContent=`${ev.length} acara`;document.getElementById('cp103DayEvents').innerHTML=ev.length?ev.map(n=>`<div style="padding:8px;border-bottom:1px solid #eee8dc;cursor:pointer" data-event="${esc(n.id)}"><b>${esc(n.title)}</b><div class="cp103-muted">${n.eventLocation?esc(n.eventLocation)+' · ':''}${SecurityService.stripHtml(n.bodyHTML||'').slice(0,120)}</div></div>`).join(''):'<div class="cp103-muted">Tidak ada acara pada tanggal ini.</div>';document.querySelectorAll('[data-event]').forEach(x=>x.onclick=()=>{this.switchTab('home');this.ctx.openNote(x.dataset.event);});},
  async batchDelete(){const ids=this.ctx.getSelectedIds();if(!ids.length)return; if(!confirm(`Hapus ${ids.length} catatan terpilih?`))return;await this.ctx.batchDelete(ids);this.ctx.clearSelection();this.syncBatchBar();},
  async batchMove(){const ids=this.ctx.getSelectedIds();if(!ids.length)return;const cats=this.ctx.getCategories().filter(c=>!c.core||c.id!=='keuangan').map(c=>`${c.id} = ${c.name}`).join('\n');const target=prompt(`Pilih ID kategori:\n${cats}`);if(!target)return;await this.ctx.batchMove(ids,target.trim());this.ctx.clearSelection();this.syncBatchBar();},
  batchExport(){const ids=this.ctx.getSelectedIds();if(!ids.length)return;const data=this.ctx.getNotes().filter(n=>ids.includes(n.id));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({app:'Catatan Pintar',notes:data},null,2)],{type:'application/json'}));a.download='catatan-terpilih.json';a.click();URL.revokeObjectURL(a.href);},
  syncBatchBar(){const ids=this.ctx?.getSelectedIds?.()||[];const b=document.getElementById('cp103Batch');if(!b)return;b.classList.toggle('open',ids.length>0);const c=document.getElementById('cp103BatchCount');if(c)c.textContent=`${ids.length} dipilih`;},
  buildImageModal(){if(document.getElementById('cp103ImageModal'))return;const m=document.createElement('div');m.id='cp103ImageModal';m.className='cp103-modal';m.innerHTML=`<div class="cp103-dialog"><div class="cp103-head"><div class="cp103-title">🖼️ Anotasi Gambar</div><button class="cp103-btn" id="cp103ImgClose">Tutup</button></div><div class="cp103-tools"><button data-tool="pen">✏️ Pena</button><button data-tool="line">╱ Garis</button><button data-tool="rect">□ Kotak</button><button data-tool="ellipse">○ Elips</button><button data-tool="arrow">➜ Panah</button><button data-tool="eraser">⌫ Penghapus</button><button id="cp103ImgText">Teks</button><input type="color" id="cp103ImgColor" value="#a3402f"><input type="range" id="cp103ImgSize" min="1" max="20" value="4"><button id="cp103ImgUndo">Undo</button><button id="cp103ImgRedo">Redo</button><button id="cp103ImgClear">Bersihkan</button></div><div class="cp103-canvas-wrap"><canvas id="cp103ImgBase"></canvas><canvas id="cp103ImgDraw" style="position:absolute;left:8px;top:8px"></canvas></div><div class="cp103-actions" style="justify-content:flex-end;margin-top:8px"><button class="cp103-btn" id="cp103ImgCancel">Batal</button><button class="cp103-btn primary" id="cp103ImgSave">Simpan sebagai lampiran</button></div></div>`;document.body.appendChild(m);const wrap=m.querySelector('.cp103-canvas-wrap');wrap.style.position='relative';wrap.style.minHeight='180px';const base=m.querySelector('#cp103ImgBase'),draw=m.querySelector('#cp103ImgDraw');ImageEditorService.init(base,draw);m.querySelector('#cp103ImgClose').onclick=m.querySelector('#cp103ImgCancel').onclick=()=>m.classList.remove('open');m.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>ImageEditorService.setTool(b.dataset.tool));m.querySelector('#cp103ImgColor').oninput=e=>ImageEditorService.setColor(e.target.value);m.querySelector('#cp103ImgSize').oninput=e=>ImageEditorService.setSize(e.target.value);m.querySelector('#cp103ImgUndo').onclick=()=>ImageEditorService.undo();m.querySelector('#cp103ImgRedo').onclick=()=>ImageEditorService.redo();m.querySelector('#cp103ImgClear').onclick=()=>ImageEditorService.clear();m.querySelector('#cp103ImgText').onclick=()=>{ImageEditorService.setTool('text');const t=prompt('Teks anotasi:');if(t){ImageEditorService.addText(20,30,t);}};m.querySelector('#cp103ImgSave').onclick=()=>{const data=ImageEditorService.exportFlattened();const att={id:id('img'),name:`anotasi_${new Date().toISOString().slice(0,10)}.png`,mime:'image/png',ext:'png',size:Math.round(data.length*.75),dataURL:data,kind:'image',createdAt:Date.now()};this.ctx.addAttachment(att);m.classList.remove('open');this.ctx.toast('Gambar beranotasi ditambahkan.','info');};},
  openImageEditor(){if(!document.getElementById('cp103ImageModal'))this.buildImageModal();let input=document.getElementById('cp103ImagePicker');if(!input){input=document.createElement('input');input.type='file';input.accept='image/*';input.id='cp103ImagePicker';input.style.display='none';document.body.appendChild(input);input.onchange=async()=>{const f=input.files?.[0];input.value='';if(!f)return;const reader=new FileReader();reader.onload=async()=>{try{await ImageEditorService.loadImage(reader.result);document.getElementById('cp103ImageModal').classList.add('open');}catch(e){this.ctx.toast(e.message,'danger');}};reader.readAsDataURL(f);};}input.click();}
};
